<?xml version="1.0"?>

<robot name="scout_mini"
    xmlns:xacro="http://ros.org/wiki/xacro">

    <xacro:arg name="robot_namespace" default="/" />

    <xacro:include filename="$(find scout_description)/urdf/scout_mini_wheel.xacro" />


    <!-- Variables -->
    <xacro:property name="M_PI" value="3.14159" />

    <!-- Vehicle Geometries -->
    <xacro:property name="base_x_size" value="0.6200000" />
    <xacro:property name="base_y_size" value="0.585000" />
    <xacro:property name="base_z_size" value="0.235000" />

    <xacro:property name="wheelbase" value="0.38" />
    <xacro:property name="track" value="0.452598" />

    <xacro:property name="wheel_length" value="0.08" />
    <xacro:property name="wheel_radius" value="0.08" />

    <!-- Base link -->
    <link name="base_link">
        <visual>
            <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0" />
            <geometry>
                <mesh filename="package://scout_description/meshes/scout_mini_base.obj" />
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0" />
            <geometry>
                <box size="${base_x_size} ${base_y_size} ${base_z_size}"/>
            </geometry>
        </collision>
    </link>

    <link name="base_footprint"/>

    <joint name="base_footprint_joint" type="fixed">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="base_footprint" />
    </joint>

    <link name="inertial_link">
        <inertial>
            <mass value="132.3898489950015" />
            <origin xyz="0 0 ${wheel_radius}" />
            <inertia ixx="0.185196122711036" ixy="4.30144213829512E-08" ixz="5.81037523686401E-08" iyy="0.364893736238929" iyz="-0.000386720198091934" izz="0.223868521722778" />
        </inertial>
    </link>

    <joint name="inertial_joint" type="fixed">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="inertial_link" />
    </joint>

    <!-- Scout wheel macros -->
    <!-- wheel labeled from 0 to 3, conter-clockwise, starting from front right wheel -->
    <!-- motor 1 and 2 (left side) are mechanically installed in a reversed direction -->
    <xacro:scout_mini_wheel wheel_prefix="rear_right">
        <origin xyz="${-wheelbase/2} ${-track/2} ${wheel_radius}" rpy="0 ${ M_PI/2} 0" />
    </xacro:scout_mini_wheel>
    <xacro:scout_mini_wheel wheel_prefix="front_right">
        <origin xyz="${-wheelbase/2} ${ track/2} ${wheel_radius}" rpy="0 ${ M_PI/2} 0" />
    </xacro:scout_mini_wheel>

    <xacro:scout_mini_wheel wheel_prefix="front_left">
        <origin xyz="${ wheelbase/2} ${ track/2} ${wheel_radius}" rpy="0 ${-M_PI/2} 0" />
    </xacro:scout_mini_wheel>
    <xacro:scout_mini_wheel wheel_prefix="rear_left">
        <origin xyz="${ wheelbase/2} ${-track/2} ${wheel_radius}" rpy="0 ${-M_PI/2} 0" />
    </xacro:scout_mini_wheel>
</robot>